name: Analyze React Code with Ollama

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  analyze-react-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          echo "Starting Ollama server in background..."
          nohup ollama serve > /dev/null 2>&1 &
          sleep 10

      - name: Pull lightweight model (e.g., mistral:7b-q4_K_M)
        run: |
          ollama pull mistral

      - name: Analyze React code in src/ folder
        run: |
          echo "Analyzing files in src/ folder..."
          for file in $(find src -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" \)); do
            echo "======================"
            echo " Analyzing: $file"
            echo "======================"
            PROMPT="Analyze this React code. Point out bugs, anti-patterns, or improvements:\n$(cat "$file")"
            echo -e "$PROMPT" | ollama run mistral:7b-q4_K_M
            echo ""
          done
